In [17]:
import pandas as pd
from pathlib import Path
import sys

sys.path.insert(1, r"..\config")

In [18]:
from paths import DISC_STANDARDS_RAW

raw = pd.read_excel(DISC_STANDARDS_RAW / "EFRAG IG 3 List of ESRS Data Points.xlsx", skiprows=1, sheet_name='ESRS E1')

raw.head()

,ID,ESRS,DR,Paragraph,Related AR,Name,Data Type,Conditional or alternative DP,May \n[V],Appendix B - ESRS 2 \n(SFDR + PILLAR 3 + Benchmark + CL),Appendix C - ESRS 1\nDPs subject to phasing-in provisions applicable to undertaking with less than 750 employees,Appendix C - ESRS 1\nDPs subject to phasing-in provisions applicable to all undertakings
0,E1.GOV-3_01,E1,E1.GOV-3,13,NaN,Disclosure of whether and how climate-related ...,narrative,NaN,NaN,NaN,NaN,NaN
1,E1.GOV-3_02,E1,E1.GOV-3,13,NaN,Percentage of remuneration recognised that is ...,percent,NaN,NaN,NaN,NaN,NaN
2,E1.GOV-3_03,E1,E1.GOV-3,13,NaN,Explanation of climate-related considerations ...,narrative,NaN,NaN,NaN,NaN,NaN
3,E1-1_01,E1,E1-1,14,AR 1,Disclosure of transition plan for climate cha...,narrative,NaN,NaN,CL,NaN,NaN
4,E1-1_02,E1,E1-1,16 a,AR 2,Explanation of how targets are compatible with...,narrative,NaN,NaN,NaN,NaN,NaN

In [19]:
req_keys = [
    'ESRS',
    'DR',
    'Paragraph',
    'Related AR',
    'Name',
    'Data Type',
    'Conditional or alternative DP'
]

unfiltered_dict = raw.loc[:, req_keys]

unfiltered_dict = unfiltered_dict.astype(str)

In [20]:
unfiltered_dict = unfiltered_dict.apply(lambda x: x.str.strip())

In [21]:
unfiltered_dict.head()

,ESRS,DR,Paragraph,Related AR,Name,Data Type,Conditional or alternative DP
0,E1,E1.GOV-3,13,nan,Disclosure of whether and how climate-related ...,narrative,nan
1,E1,E1.GOV-3,13,nan,Percentage of remuneration recognised that is ...,percent,nan
2,E1,E1.GOV-3,13,nan,Explanation of climate-related considerations ...,narrative,nan
3,E1,E1-1,14,AR 1,Disclosure of transition plan for climate cha...,narrative,nan
4,E1,E1-1,16 a,AR 2,Explanation of how targets are compatible with...,narrative,nan

In [22]:
nested = (
    unfiltered_dict.groupby(["ESRS", "DR", "Paragraph"], dropna=False)
      .apply(lambda g: g[["Related AR", "Name", "Data Type", "Conditional or alternative DP"]]
             .rename(columns={
                 "Related AR": "AR",
                 "Data Type": "datatype",
                 "Conditional or alternative DP": "dp_type"
                 })
             .to_dict(orient="records"), include_groups=False)
      .reset_index(name="entries")
)

In [23]:
level1 = (
    nested.groupby("ESRS")
    .apply(lambda g: g.groupby("DR")
           .apply(lambda h: dict(zip(h["Paragraph"], h["entries"])), include_groups=False)
           .to_dict(), include_groups=False)
    .to_dict()
)

In [24]:
level1

{'E1': {'E1-1': {'14': [{'AR': 'AR 1',
     'Name': 'Disclosure of transition plan  for climate change mitigation',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   '16 a': [{'AR': 'AR 2',
     'Name': 'Explanation of how targets are compatible with limiting of global warming to one and half degrees Celsius in line with Paris Agreement',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   '16 b': [{'AR': 'nan',
     'Name': 'Disclosure of decarbonisation levers and key action',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   '16 c': [{'AR': 'nan',
     'Name': 'Disclosure of significant operational expenditures (Opex) and (or) capital expenditures (Capex) required for implementation of action plan',
     'datatype': 'narrative',
     'dp_type': 'nan'},
    {'AR': 'nan',
     'Name': 'Financial resources allocated to action plan (OpEx)',
     'datatype': 'monetary',
     'dp_type': 'nan'},
    {'AR': 'nan',
     'Name': 'Financial resources allocated to action plan (CapEx)',
     'datatype': 'monetary',
     'dp_type': 'nan'}],
   '16 d': [{'AR': 'AR 3',
     'Name': 'Explanation of potential locked-in GHG emissions from key assets and products and of how locked-in GHG emissions may jeopardise achievement of GHG emission reduction targets and drive transition risk',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   '16 e': [{'AR': 'AR 4',
     'Name': 'Explanation of any objective or plans (CapEx, CapEx plans, OpEx) for aligning economic activities (revenues, CapEx, OpEx) with criteria established in Commission Delegated Regulation 2021/2139',
     'datatype': 'narrative',
     'dp_type': 'Conditional'}],
   '16 f': [{'AR': 'AR 5',
     'Name': 'Significant CapEx for coal-related economic activities',
     'datatype': 'monetary',
     'dp_type': 'Conditional'},
    {'AR': 'AR 5',
     'Name': 'Significant CapEx for oil-related economic activities',
     'datatype': 'monetary',
     'dp_type': 'Conditional'},
    {'AR': 'AR 5',
     'Name': 'Significant CapEx for gas-related economic activities',
     'datatype': 'monetary',
     'dp_type': 'Conditional'}],
   '16 g': [{'AR': 'nan',
     'Name': 'Undertaking is excluded from EU Paris-aligned Benchmarks',
     'datatype': 'semi-narrative',
     'dp_type': 'nan'}],
   '16 h': [{'AR': 'nan',
     'Name': 'Explanation of how transition plan is embedded in and aligned with overall business strategy and financial planning',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   '16 i': [{'AR': 'nan',
     'Name': 'Transition plan is approved by administrative, management and supervisory bodies',
     'datatype': 'semi-narrative',
     'dp_type': 'nan'}],
   '16 j': [{'AR': 'nan',
     'Name': 'Explanation of progress in implementing transition plan',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   '17': [{'AR': 'nan',
     'Name': 'Date of adoption of transition plan for undertakings not having adopted transition plan yet',
     'datatype': 'gYear',
     'dp_type': 'Conditional'}]},
  'E1-2': {'24': [{'AR': 'nan',
     'Name': 'Policies in place to manage its material impacts, risks and opportunities related to climate change mitigation and adaptation [see ESRS 2 MDR-P]',
     'datatype': 'MDR-P',
     'dp_type': 'nan'}],
   '25': [{'AR': 'AR 16-AR18',
     'Name': 'Sustainability matters addressed by policy for climate change',
     'datatype': 'semi-narrative',
     'dp_type': 'nan'}]},
  'E1-3': {'28': [{'AR': 'nan',
     'Name': 'Actions and Resources related to climate change mitigation and adaptation [see ESRS 2 MDR-A]',
     'datatype': 'MDR-A',
     'dp_type': 'nan'}],
   '29 a': [{'AR': 'nan',
     'Name': 'Decarbonisation lever type',
     'datatype': 'semi-narrative',
     'dp_type': 'nan'}],
   '29 b': [{'AR': 'nan',
     'Name': 'Achieved GHG emission reductions',
     'datatype': 'ghgEmissions',
     'dp_type': 'nan'},
    {'AR': 'nan',
     'Name': 'Expected GHG emission reductions',
     'datatype': 'ghgEmissions',
     'dp_type': 'nan'}],
   '29 c i': [{'AR': 'AR 20',
     'Name': 'Explanation of relationship of significant CapEx and OpEx required to implement actions taken or planned to relevant line items or notes in financial statements',
     'datatype': 'narrative/monetary',
     'dp_type': 'nan'}],
   '29 c ii,16 c': [{'AR': 'AR 22',
     'Name': 'Explanation of relationship of significant CapEx and OpEx required to implement actions taken or planned to key performance indicators required under Commission Delegated Regulation (EU) 2021/2178',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   '29 c iii,16 c': [{'AR': 'AR 20',
     'Name': 'Explanation of relationship of significant CapEx and OpEx required to implement actions taken or planned to CapEx plan required by Commission Delegated Regulation (EU) 2021/2178',
     'datatype': 'narrative',
     'dp_type': 'Conditional'}],
   'AR19d': [{'AR': 'nan',
     'Name': 'Adaptation solution type',
     'datatype': 'semi-narrative',
     'dp_type': 'nan'}],
   'AR21': [{'AR': 'nan',
     'Name': 'Explanation of extent to which ability to implement action depends on availability and allocation of resources',
     'datatype': 'narrative',
     'dp_type': 'nan'}]},
  'E1-4': {'32': [{'AR': 'nan',
     'Name': 'Tracking effectiveness of policies and actions through targets [see ESRS 2 MDR-T ]',
     'datatype': 'MDR-T',
     'dp_type': 'nan'}],
   '33': [{'AR': 'AR 27-AR 29',
     'Name': 'Disclosure of whether and how GHG emissions reduction targets and (or) any other targets have been set to manage material climate-related impacts, risks and opportunities',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   '34 a + 34  b': [{'AR': 'AR 23-AR 24, AR 27-AR 29, AR31',
     'Name': 'Tables: Multiple Dimensions (baseline year and targets; GHG Types, Scope 3 Categories, Decarbonisation levers, entity-specific denominators for intensity value)',
     'datatype': 'Table',
     'dp_type': 'Conditional'}],
   '34 a + 34 b': [{'AR': 'nan',
     'Name': 'Absolute value of total Greenhouse gas emissions reduction',
     'datatype': 'Table/ghgEmissions',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Percentage of total Greenhouse gas emissions reduction (as of emissions of base year)',
     'datatype': 'Table/percent',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Intensity value of total Greenhouse gas emissions reduction',
     'datatype': 'Table/decimal',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Absolute value of Scope 1 Greenhouse gas emissions reduction',
     'datatype': 'Table/ghgEmissions',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Percentage of Scope 1 Greenhouse gas emissions reduction (as of emissions of base year)',
     'datatype': 'Table/percent',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Intensity value of Scope 1 Greenhouse gas emissions reduction',
     'datatype': 'Table/decimal',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Absolute value of location-based Scope 2 Greenhouse gas emissions reduction',
     'datatype': 'Table/ghgEmissions',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Percentage of location-based Scope 2 Greenhouse gas emissions reduction (as of emissions of base year)',
     'datatype': 'Table/percent',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Intensity value of location-based Scope 2 Greenhouse gas emissions reduction',
     'datatype': 'Table/decimal',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Absolute value of market-based Scope 2 Greenhouse gas emissions reduction',
     'datatype': 'Table/ghgEmissions',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Percentage of market-based Scope 2 Greenhouse gas emissions reduction (as of emissions of base year)',
     'datatype': 'Table/percent',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Intensity value of market-based Scope 2 Greenhouse gas emissions reduction',
     'datatype': 'Table/decimal',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Absolute value of Scope 3 Greenhouse gas emissions reduction',
     'datatype': 'Table/ghgEmissions',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Percentage of Scope 3 Greenhouse gas emissions reduction (as of emissions of base year)',
     'datatype': 'Table/percent',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Intensity value of Scope 3 Greenhouse gas emissions reduction',
     'datatype': 'Table/decimal',
     'dp_type': 'Conditional'}],
   '34 b': [{'AR': 'nan',
     'Name': 'Explanation of how consistency of GHG emission reduction targets with GHG inventory boundaries has been ensured',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   '34 c': [{'AR': 'nan',
     'Name': 'Disclosure of past progress made in meeting target before current base year',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   '34 e, 16 a': [{'AR': 'AR 26',
     'Name': 'GHG emission reduction target is science based and compatible with limiting global warming to one and half degrees Celsius',
     'datatype': 'semi-narrative',
     'dp_type': 'nan'}],
   '34 f, 16 b': [{'AR': 'AR 30',
     'Name': 'Description of expected decarbonisation levers and their overall quantitative contributions to achieve GHG emission reduction target',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   'AR 25 a': [{'AR': 'nan',
     'Name': 'Description of how it has been ensured that baseline value is representative in terms of activities covered and influences from external factors',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   'AR 25 b': [{'AR': 'nan',
     'Name': 'Description of how new baseline value affects new target, its achievement and presentation of progress over time',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   'AR 30 c': [{'AR': 'nan',
     'Name': 'Diverse range of climate scenarios have been considered to detect relevant environmental, societal, technology, market and policy-related developments and determine decarbonisation levers',
     'datatype': 'narrative',
     'dp_type': 'nan'}]},
  'E1-5': {'37': [{'AR': 'AR 35',
     'Name': 'Total energy consumption related to own operations',
     'datatype': 'energy',
     'dp_type': 'nan'}],
   '37 a': [{'AR': 'AR 33, AR 32',
     'Name': 'Total energy consumption from fossil sources',
     'datatype': 'energy',
     'dp_type': 'nan'}],
   '37 b': [{'AR': 'nan',
     'Name': 'Total energy consumption from nuclear sources',
     'datatype': 'energy',
     'dp_type': 'nan'}],
   '37 c': [{'AR': 'nan',
     'Name': 'Total energy consumption from renewable sources',
     'datatype': 'energy',
     'dp_type': 'nan'}],
   '37 c i': [{'AR': 'nan',
     'Name': 'Fuel consumption from renewable sources',
     'datatype': 'energy',
     'dp_type': 'nan'}],
   '37 c ii': [{'AR': 'nan',
     'Name': 'Consumption of purchased or acquired electricity, heat, steam, and cooling from renewable sources',
     'datatype': 'energy',
     'dp_type': 'nan'}],
   '37 c iii': [{'AR': 'nan',
     'Name': 'Consumption of self-generated non-fuel renewable energy',
     'datatype': 'energy',
     'dp_type': 'nan'}],
   '38 a': [{'AR': 'AR 33',
     'Name': 'Fuel consumption from coal and coal products',
     'datatype': 'energy',
     'dp_type': 'Conditional'}],
   '38 b': [{'AR': 'AR 33',
     'Name': 'Fuel consumption from crude oil and petroleum products',
     'datatype': 'energy',
     'dp_type': 'Conditional'}],
   '38 c': [{'AR': 'AR 33',
     'Name': 'Fuel consumption from natural gas',
     'datatype': 'energy',
     'dp_type': 'Conditional'}],
   '38 d': [{'AR': 'AR 33',
     'Name': 'Fuel consumption from other fossil sources',
     'datatype': 'energy',
     'dp_type': 'Conditional'}],
   '38 e': [{'AR': 'AR 33',
     'Name': 'Consumption of purchased or acquired electricity, heat, steam, or cooling from fossil sources',
     'datatype': 'energy',
     'dp_type': 'Conditional'}],
   '39': [{'AR': 'nan',
     'Name': 'Non-renewable energy production',
     'datatype': 'energy',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Renewable energy production',
     'datatype': 'energy',
     'dp_type': 'Conditional'}],
   '40': [{'AR': 'AR 36',
     'Name': 'Energy intensity from activities in high climate impact sectors (total energy consumption per net revenue)',
     'datatype': 'percent',
     'dp_type': 'Conditional'}],
   '41': [{'AR': 'nan',
     'Name': 'Total energy consumption from activities in high climate impact sectors',
     'datatype': 'Intensity',
     'dp_type': 'Conditional'}],
   '42': [{'AR': 'nan',
     'Name': 'High climate impact sectors used to determine energy intensity',
     'datatype': 'semi-narrative',
     'dp_type': 'Conditional'}],
   '43': [{'AR': 'AR 38',
     'Name': 'Disclosure of reconciliation to relevant line item or notes in financial statements of net revenue from activities in high climate impact sectors',
     'datatype': 'narrative',
     'dp_type': 'Conditional'}],
   'AR 34': [{'AR': 'nan',
     'Name': 'Percentage of energy consumption from nuclear sources in total energy consumption',
     'datatype': 'percent',
     'dp_type': 'nan'},
    {'AR': 'nan',
     'Name': 'Percentage of renewable sources in total energy consumption',
     'datatype': 'percent',
     'dp_type': 'nan'},
    {'AR': 'nan',
     'Name': 'Percentage of fossil sources in total energy consumption',
     'datatype': 'percent',
     'dp_type': 'Conditional'}],
   'AR 38 b': [{'AR': 'nan',
     'Name': 'Net revenue from activities in high climate impact sectors',
     'datatype': 'monetary',
     'dp_type': 'Conditional'},
    {'AR': 'nan',
     'Name': 'Net revenue from activities other than in high climate impact sectors',
     'datatype': 'monetary',
     'dp_type': 'Conditional'}]},
  'E1-6': {'44': [{'AR': 'AR 39',
     'Name': 'Gross Scopes 1, 2, 3 and Total GHG emissions - GHG emissions per scope [table]',
     'datatype': 'Table',
     'dp_type': 'nan'}],
   '44, 52 a': [{'AR': 'AR 47',
     'Name': 'Total GHG emissions location based',
     'datatype': 'Table/GhgEmissions',
     'dp_type': 'nan'}],
   '44, 52 b': [{'AR': 'AR 47',
     'Name': 'Total GHG emissions market based',
     'datatype': 'Table/GhgEmissions',
     'dp_type': 'nan'}],
   '47': [{'AR': 'nan',
     'Name': 'Disclosure of significant changes in definition of what constitutes reporting undertaking and its value chain and explanation of their effect on year-to-year comparability of reported GHG emissions',
     'datatype': 'narrative',
     'dp_type': 'Conditional'}],
   '48 a': [{'AR': 'AR 43',
     'Name': 'Gross Scope 1 greenhouse gas emissions',
     'datatype': 'Table/GhgEmissions',
     'dp_type': 'nan'}],
   '48 b': [{'AR': 'AR 44',
     'Name': 'Percentage of Scope 1 GHG emissions from regulated emission trading schemes',
     'datatype': 'Table/Percent',
     'dp_type': 'nan'}],
   '49 a, 52 a': [{'AR': 'AR 45, AR 47',
     'Name': 'Gross location-based Scope 2 greenhouse gas emissions',
     'datatype': 'Table/GhgEmissions',
     'dp_type': 'nan'}],
   '49 b, 52 b': [{'AR': 'AR 45, AR 47',
     'Name': 'Gross market-based Scope 2 greenhouse gas emissions',
     'datatype': 'Table/GhgEmissions',
     'dp_type': 'nan'}],
   '50': [{'AR': 'nan',
     'Name': 'Gross Scopes 1, 2, 3 and Total GHG emissions - financial and operational control [table]',
     'datatype': 'Table',
     'dp_type': 'nan'}],
   '51': [{'AR': 'AR 46',
     'Name': 'Gross Scope 3 greenhouse gas emissions',
     'datatype': 'Table/GhgEmissions',
     'dp_type': 'nan'}],
   '53': [{'AR': 'AR 53',
     'Name': 'GHG emissions intensity, location-based (total GHG emissions per net revenue)',
     'datatype': 'Intensity',
     'dp_type': 'nan'},
    {'AR': 'AR 53',
     'Name': 'GHG emissions intensity, market-based (total GHG emissions per net revenue)',
     'datatype': 'Intensity',
     'dp_type': 'nan'}],
   '55': [{'AR': 'nan',
     'Name': 'Disclosure of reconciliation to financial statements of net revenue used for calculation of GHG emissions intensity',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   'AR 39 b': [{'AR': 'nan',
     'Name': 'Disclosure of methodologies, significant assumptions and emissions factors used to calculate or measure GHG emissions',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   'AR 41': [{'AR': 'nan',
     'Name': 'Disaggregation of GHG emissions - by country, operating segments, economic activity, subsidiary, GHG category or source type',
     'datatype': 'Table',
     'dp_type': 'nan'}],
   'AR 42 c': [{'AR': 'nan',
     'Name': 'Disclosure of the effects of significant events and changes in circumstances (relevant to its GHG emissions) that occur between the reporting dates of the entities in its value chain and the date of the undertaking’s general purpose financial statements',
     'datatype': 'narrative',
     'dp_type': 'Conditional'}],
   'AR 43 c': [{'AR': 'nan',
     'Name': 'biogenic emissions of CO2 from the combustion or bio-degradation of biomassnot included in Scope 1 GHG emissions',
     'datatype': 'ghgEmissions',
     'dp_type': 'nan'}],
   'AR 45 d': [{'AR': 'nan',
     'Name': 'Percentage of contractual instruments, Scope 2 GHG emissions',
     'datatype': 'percent',
     'dp_type': 'nan'},
    {'AR': 'nan',
     'Name': 'Disclosure of types of contractual instruments, Scope 2 GHG emissions',
     'datatype': 'percent',
     'dp_type': 'nan'},
    {'AR': 'nan',
     'Name': 'Percentage of market-based Scope 2 GHG emissions linked to purchased electricity bundled with instruments',
     'datatype': 'percent',
     'dp_type': 'nan'},
    {'AR': 'nan',
     'Name': 'Percentage of contractual instruments used for sale and purchase of energy bundled with attributes about energy generation in relation to Scope 2 GHG emissions',
     'datatype': 'percent',
     'dp_type': 'nan'},
    {'AR': 'nan',
     'Name': 'Percentage of contractual instruments used for sale and purchase of unbundled energy attribute claims in relation to Scope 2 GHG emissions',
     'datatype': 'percent',
     'dp_type': 'nan'},
    {'AR': 'nan',
     'Name': 'Disclosure of types of contractual instruments used for sale and purchase of energy bundled with attributes about energy generation or for unbundled energy attribute claims',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   'AR 45 e': [{'AR': 'nan',
     'Name': 'Biogenic emissions of CO2 from combustion or bio-degradation of biomass not included in Scope 2 GHG emissions',
     'datatype': 'ghgEmissions',
     'dp_type': 'nan'}],
   'AR 46 d': [{'AR': 'nan',
     'Name': 'Gross Scopes 1, 2, 3 and Total GHG emissions - Scope 3 GHG emissions (GHG Protocol) [table]',
     'datatype': 'Table',
     'dp_type': 'Alternative'}],
   'AR 46 g': [{'AR': 'nan',
     'Name': 'Percentage of GHG Scope 3 calculated using primary data',
     'datatype': 'Percent',
     'dp_type': 'nan'}],
   'AR 46 h': [{'AR': 'nan',
     'Name': 'Disclosure of reporting boundaries considered and calculation methods for estimating Scope 3 GHG emissions',
     'datatype': 'narrative',
     'dp_type': 'nan'}],
   'AR 46 i': [{'AR': 'nan',
     'Name': 'Disclosure of why Scope 3 GHG emissions category has been excluded',
     'datatype': 'narrative',
     'dp_type': 'nan'},
    {'AR': 'nan',
     'Name': 'List of Scope 3 GHG emissions categories included in inventory',
     'datatype': 'semi-narrative',
     'dp_type': 'nan'}],
   'AR 46 j': [{'AR': 'nan',
     'Name': 'Biogenic emissions of CO2 from combustion or bio-degradation of biomass that occur in value chain not included in Scope 3 GHG emissions',
     'datatype': 'ghgEmissions',
     'dp_type': 'nan'}],
   'AR 50': [{'AR': 'nan',