### trying to use the excel

In [1]:
import pandas as pd

In [2]:
x = pd.read_excel(r'..\disclosure_standards\raw\esrs_paragraph_mapping.xlsx', sheet_name="esrse1")

In [4]:
x.head()

,paragraph,details,nested1,nested2,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1,The objective of this Standard is to specify D...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,(a),"how the undertaking affects climate change, in...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,(b),"the undertaking’s past, current, and future mi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,(c),the plans and capacity of the undertaking to a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,(d),"any other actions taken by the undertaking, an...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
maybe_tables = x.groupby(["paragraph", "details"]).filter(lambda x: len(x) > 1)

tables = maybe_tables.groupby(["paragraph", "details"]).filter(lambda x: (x["nested1"].fillna('').str.len() > 3).all())

# tables.groupby(["paragraph", "details"]).agg(' '.join, axis=1)

tables.groupby(["paragraph", "details"]).agg(' '.join, axis=1)

TypeError: str.join() takes exactly one argument (0 given)

In [39]:
df = tables.groupby(["paragraph", "details"]).get_group(('AR 12.', '(d)'))

df.head()

,paragraph,details,nested1,nested2,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
216,AR 12.,(d),identified assets and business activities that...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,AR 12.,(d),Examples of climate-related transition events ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,AR 12.,(d),Policy and legal,Technology,Market,Reputation,NaN,NaN,NaN,NaN,NaN
219,AR 12.,(d),Increased pricing of GHG emissions,Substitution of existing products and services...,Changing customer behaviour,Shifts in consumer preferences,NaN,NaN,NaN,NaN,NaN
220,AR 12.,(d),Enhanced emissions- reporting obligations,Unsuccessful investment in new technologies,Uncertainty in market signals,Stigmatization of sector,NaN,NaN,NaN,NaN,NaN

In [34]:
' '.join(tables.iloc[:, 2:].astype(str).values.flatten())

'identified assets and business activities that are incompatible with or need significant efforts to be compatible with a transition to a climate-neutral economy (for example, due to significant locked-in GHG emissions or incompatibility with the requirements for Taxonomy-alignment under Commission Delegated Regulation (EU)\xa02021/2139). nan nan nan nan nan nan nan nan Examples of climate-related transition events (examples based on TCFD classification)  nan nan nan nan nan nan nan nan Policy and legal  Technology  Market  Reputation  nan nan nan nan nan Increased pricing of GHG emissions Substitution of existing products and services with lower emissions options Changing customer behaviour Shifts in consumer preferences nan nan nan nan nan Enhanced emissions- reporting obligations Unsuccessful investment in new technologies Uncertainty in market signals Stigmatization of sector nan nan nan nan nan Mandates on and regulation of existing products and services Costs of transition to lower emissions technology Increased cost of raw materials Increased stakeholder concern nan nan nan nan nan Mandates on and regulation of existing production processes nan nan Negative stakeholder feedback nan nan nan nan nan Exposure to litigation nan nan nan nan nan nan nan nan If the net revenue cannot be directly cross-referenced to a line item or disclosure in the financial statements, by a quantitative reconciliation using the below tabular format. nan nan nan nan nan nan nan nan Net revenue from activities in high climate impact sectors used to calculate energy intensity nan nan nan nan nan nan nan nan Net revenue (other) nan nan nan nan nan nan nan nan Total net revenue (Financial statements) nan nan nan nan nan nan nan nan calculate the share by using the following formula: nan nan nan nan nan nan nan nan GHG Emissions in (t CO 2 eq) from EU ETS installations + national ETS installations + nonEU ETS installations nan nan nan nan nan nan nan nan Scope 1 GHG emissions (t CO2eq) nan nan nan nan nan nan nan nan Fuel and energy-related nan nan nan nan nan nan nan nan Activities (not included in Scope1 or Scope 2) nan nan nan nan nan nan nan nan if the net revenue cannot be directly cross-referenced to a line item or disclosure in the financial statements, by a quantitative reconciliation using the below tabular format. nan nan nan nan nan nan nan nan Net revenue used to calculate GHG intensity nan nan nan nan nan nan nan nan Net revenue (other) nan nan nan nan nan nan nan nan Total net revenue (in financial statements) nan nan nan nan nan nan nan nan If these cannot be directly cross-referenced, as a quantitative reconciliation of each to the relevant line item or disclosure in the financial statement using the below tabular format: nan nan nan nan nan nan nan nan Carrying amount of assets or liabilities or net revenue vulnerable to either material physical or transition risks nan nan nan nan nan nan nan nan Adjusting items nan nan nan nan nan nan nan nan Assets or liabilities or net revenue in the financial statements nan nan nan nan nan nan nan nan'

In [35]:
rows = []
for _, row in tables.iloc[:, 2:].iterrows():
    row_text = ', '.join(
        f"{col}: {row[col]}"
        for col in tables.iloc[:, 2:].columns
        if pd.notna(row[col])
    )
    rows.append(row_text)

text = ' | '.join(rows)

In [36]:
text

'nested1: identified assets and business activities that are incompatible with or need significant efforts to be compatible with a transition to a climate-neutral economy (for example, due to significant locked-in GHG emissions or incompatibility with the requirements for Taxonomy-alignment under Commission Delegated Regulation (EU)\xa02021/2139). | nested1: Examples of climate-related transition events (examples based on TCFD classification)  | nested1: Policy and legal , nested2: Technology , Unnamed: 4: Market , Unnamed: 5: Reputation  | nested1: Increased pricing of GHG emissions, nested2: Substitution of existing products and services with lower emissions options, Unnamed: 4: Changing customer behaviour, Unnamed: 5: Shifts in consumer preferences | nested1: Enhanced emissions- reporting obligations, nested2: Unsuccessful investment in new technologies, Unnamed: 4: Uncertainty in market signals, Unnamed: 5: Stigmatization of sector | nested1: Mandates on and regulation of existing products and services, nested2: Costs of transition to lower emissions technology, Unnamed: 4: Increased cost of raw materials, Unnamed: 5: Increased stakeholder concern | nested1: Mandates on and regulation of existing production processes, Unnamed: 5: Negative stakeholder feedback | nested1: Exposure to litigation | nested1: If the net revenue cannot be directly cross-referenced to a line item or disclosure in the financial statements, by a quantitative reconciliation using the below tabular format. | nested1: Net revenue from activities in high climate impact sectors used to calculate energy intensity | nested1: Net revenue (other) | nested1: Total net revenue (Financial statements) | nested1: calculate the share by using the following formula: | nested1: GHG Emissions in (t CO 2 eq) from EU ETS installations + national ETS installations + nonEU ETS installations | nested1: Scope 1 GHG emissions (t CO2eq) | nested1: Fuel and energy-related | nested1: Activities (not included in Scope1 or Scope 2) | nested1: if the net revenue cannot be directly cross-referenced to a line item or disclosure in the financial statements, by a quantitative reconciliation using the below tabular format. | nested1: Net revenue used to calculate GHG intensity | nested1: Net revenue (other) | nested1: Total net revenue (in financial statements) | nested1: If these cannot be directly cross-referenced, as a quantitative reconciliation of each to the relevant line item or disclosure in the financial statement using the below tabular format: | nested1: Carrying amount of assets or liabilities or net revenue vulnerable to either material physical or transition risks | nested1: Adjusting items | nested1: Assets or liabilities or net revenue in the financial statements'

### Trying Docling

In [41]:
from docling.document_converter import DocumentConverter

In [43]:
converter = DocumentConverter()

doc = converter.convert(r"raw\ESRS Set 1.pdf").document

2025-12-15 23:03:25,365 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-15 23:03:28,233 - INFO - Going to convert document batch...
2025-12-15 23:03:28,236 - INFO - Initializing pipeline for StandardPdfPipeline with options hash 44ae89a68fc272bc7889292e9b5a1bad
2025-12-15 23:03:28,254 - INFO - Loading plugin 'docling_defaults'
2025-12-15 23:03:28,259 - INFO - Registered picture descriptions: ['vlm', 'api']
2025-12-15 23:03:28,274 - INFO - Loading plugin 'docling_defaults'
2025-12-15 23:03:28,287 - INFO - Registered ocr engines: ['auto', 'easyocr', 'ocrmac', 'rapidocr', 'tesserocr', 'tesseract']
2025-12-15 23:03:28,425 - INFO - rapidocr cannot be used because onnxruntime is not installed.
2025-12-15 23:03:28,426 - INFO - easyocr cannot be used because it is not installed.
2025-12-15 23:03:30,436 - INFO - Accelerator device: 'cuda:0'
[INFO] 2025-12-15 23:03:30,463 [RapidOCR] base.py:22: Using engine_name: torch
[INFO] 2025-12-15 23:03:30,536 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\krish\Work\projects\esg-disclosure-classifier\venv\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_infer.pth
[INFO] 2025-12-15 23:03:30,537 [RapidOCR] torch.py:54: Using C:\Users\krish\Work\projects\esg-disclosure-classifier\venv\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_infer.pth
[INFO] 2025-12-15 23:03:31,037 [RapidOCR] base.py:22: Using engine_name: torch
[INFO] 2025-12-15 23:03:31,058 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\krish\Work\projects\esg-disclosure-classifier\venv\Lib\site-packages\rapidocr\models\ch_ptocr_mobile_v2.0_cls_infer.pth
[INFO] 2025-12-15 23:03:31,060 [RapidOCR] torch.py:54: Using C:\Users\krish\Work\projects\esg-disclosure-classifier\venv\Lib\site-packages\rapidocr\models\ch_ptocr_mobile_v2.0_cls_infer.pth
[INFO] 2025-12-15 23:03:31,208 [RapidOCR] base.py:22: Using engine_name: torch
[INFO] 2025-12-15 23:03:31,291 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\krish\Work\projects\esg-disclosure-classifier\venv\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_infer.pth
[INFO] 2025-12-15 23:03:31,292 [RapidOCR] torch.py:54: Using C:\Users\krish\Work\projects\esg-disclosure-classifier\venv\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_infer.pth
2025-12-15 23:03:31,582 - INFO - Auto OCR model selected rapidocr with torch.
2025-12-15 23:03:31,597 - INFO - Accelerator device: 'cuda:0'
2025-12-15 23:03:34,242 - INFO - Accelerator device: 'cuda:0'
2025-12-15 23:03:35,166 - INFO - Processing document ESRS Set 1.pdf
2025-12-15 23:15:14,635 - INFO - Finished converting document ESRS Set 1.pdf in 709.38 sec.

In [52]:
output_dir = r"raw/tables/"

for table_ix, table in enumerate(doc.tables):
    table_df: pd.DataFrame = table.export_to_dataframe(doc=doc)
    # print(f"## Table {table_ix}")
    # print(table_df.to_markdown())

    # Save the table as CSV
    element_csv_filename = output_dir + f"ESRS-table-{table_ix + 1}.csv"
    table_df.to_csv(element_csv_filename)

In [ ]:
doc.texts

[FormulaItem(self_ref='#/texts/0', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.FORMULA: 'formula'>, prov=[ProvenanceItem(page_no=147, bbox=BoundingBox(l=201.0, t=328.2534383138021, r=477.3333333333333, b=307.2534383138021, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 83))], orig='Numberof employeescoveredbycollective bargainingagreements X 100 Numberof employees', text='', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/1', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.FURNITURE: 'furniture'>, meta=None, label=<DocItemLabel.PAGE_FOOTER: 'page_footer'>, prov=[ProvenanceItem(page_no=147, bbox=BoundingBox(l=173.66666666666666, t=46.25343831380212, r=458.0, b=37.25343831380212, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 67))], orig="Numberofemployeesworkinginestablishmentswithworkers'representatives", text="Numberofemployeesworkinginestablishmentswithworkers'representatives", formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/2', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.FURNITURE: 'furniture'>, meta=None, label=<DocItemLabel.PAGE_FOOTER: 'page_footer'>, prov=[ProvenanceItem(page_no=147, bbox=BoundingBox(l=276.3333333333333, t=34.25343831380212, r=354.66666666666663, b=25.25343831380212, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 17))], orig='Numberofemployees', text='Numberofemployees', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/3', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.FURNITURE: 'furniture'>, meta=None, label=<DocItemLabel.PAGE_FOOTER: 'page_footer'>, prov=[ProvenanceItem(page_no=147, bbox=BoundingBox(l=467.0, t=38.92010498046875, r=488.0, b=31.92010498046875, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 4))], orig='x100', text='x100', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/4', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=151, bbox=BoundingBox(l=190.66666666666666, t=746.2534383138021, r=496.6666666666667, b=738.5867716471354, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 87))], orig='(Averagegrosshourlypaylevelofmaleemployees-averagegrosshourlypayleveloffemaleemployees)', text='(Averagegrosshourlypaylevelofmaleemployees-averagegrosshourlypayleveloffemaleemployees)', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/5', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=151, bbox=BoundingBox(l=268.0, t=725.5867716471354, r=410.66666666666663, b=717.5867716471354, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 41))], orig='Averagegrosshourlypaylevelofmaleemployees', text='Averagegrosshourlypaylevelofmaleemployees', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/6', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=151, bbox=BoundingBox(l=230.33333333333334, t=331.25343831380206, r=437.33333333333337, b=324.2534383138021, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 63))], orig="Annualtotalremunerationfortheundertaking'shighestpaidindividual", text="Annualtotalremunerationfortheundertaking'shighestpaidindividual", formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/7', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=151, bbox=BoundingBox(l=211.33333333333334, t=310.2534383138021, r=456.0, b=302.92010498046875, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 73))], orig='Medianemployeeannualtotalremuneration(excludingthehighest-paidindividual)', text='Medianemployeeannualtotalremuneration(excludingthehighest-paidindividual)', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/8', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=151, bbox=BoundingBox(l=518.3333333333333, t=735.5867716471354, r=539.0, b=728.5867716471354, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 4))], orig='x100', text='x100', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/9', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=396.33333333333337, t=827.5867716471354, r=489.3333333333333, b=818.5867716471354, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 26))], orig='Theundertakingcan omit all', text='Theundertakingcan omit all', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/10', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=158.33333333333334, t=823.5867716471354, r=300.0, b=814.9201049804688, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 39))], orig='Performtheimpactandfinancialmateriality', text='Performtheimpactandfinancialmateriality', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/11', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=396.33333333333337, t=816.2534383138021, r=495.3333333333333, b=807.5867716471354, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 27))], orig='disclosurerequirementsofthe', text='disclosurerequirementsofthe', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/12', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=157.66666666666666, t=812.5867716471354, r=305.0, b=804.5867716471354, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 37))], orig='assessment(informedbythetableinAR16in', text='assessment(informedbythetableinAR16in', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/13', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=396.0, t=805.5867716471354, r=489.0, b=797.2534383138021, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 27))], orig='topicalstandard.Butshall in', text='topicalstandard.Butshall in', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/14', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=157.66666666666666, t=801.9201049804688, r=199.33333333333334, b=792.9201049804688, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 10))], orig='AppendixA)', text='AppendixA)', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/15', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=396.0, t=796.2534383138021, r=499.6666666666667, b=785.2534383138021, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 30))], orig='case of ESRS E1 Climatechange,', text='case of ESRS E1 Climatechange,', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/16', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=396.0, t=784.2534383138021, r=496.0, b=774.9201049804688, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 28))], orig='discloseadetailedexplanation', text='discloseadetailedexplanation', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/17', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=396.33333333333337, t=772.5867716471354, r=489.0, b=763.9201049804688, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 23))], orig='ofwhyclimatechangeisnot', text='ofwhyclimatechangeisnot', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/18', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=156.33333333333334, t=762.5867716471354, r=320.0, b=754.2534383138021, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 48))], orig='Is thetopiccovered bya topical standardmaterial?', text='Is thetopiccovered bya topical standardmaterial?', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/19', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=348.66666666666663, t=760.9201049804688, r=360.0, b=752.9201049804688, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 2))], orig='No', text='No', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/20', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=395.66666666666663, t=761.9201049804688, r=487.0, b=752.9201049804688, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 23))], orig='materialandmaydisclosea', text='materialandmaydisclosea', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/21', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=242.66666666666669, t=749.5867716471354, r=249.0, b=743.5867716471354, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 1))], orig='T', text='T', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/22', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=396.33333333333337, t=750.9201049804688, r=496.3333333333333, b=741.9201049804688, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 27))], orig='briefexplanationinthecaseof', text='briefexplanationinthecaseof', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/23', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=238.66666666666669, t=742.2534383138021, r=251.66666666666669, b=732.2534383138021, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 3))], orig='Yes', text='Yes', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/24', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=396.33333333333337, t=739.9201049804688, r=495.0, b=731.2534383138021, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 27))], orig='othertopicalstandards(ESRS1', text='othertopicalstandards(ESRS1', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/25', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=415.0, t=707.2534383138021, r=485.3333333333333, b=698.2534383138021, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 19))], orig='Theundertakingshall', text='Theundertakingshall', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/26', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=176.66666666666666, t=693.2534383138021, r=215.0, b=685.2534383138021, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 10))], orig='Formetrics', text='Formetrics', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/27', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=415.0, t=696.2534383138021, r=486.3333333333333, b=687.5867716471354, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 19))], orig='disclosethistobethe', text='disclosethistobethe', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/28', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=267.3333333333333, t=691.5867716471354, r=333.66666666666663, b=681.2534383138021, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 19))], orig='Has the undertaking', text='Has the undertaking', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/29', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=414.3333333333333, t=685.5867716471354, r=487.6666666666667, b=675.9201049804688, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 17))], orig='caseandmayreporta', text='caseandmayreporta', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/30', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=267.3333333333333, t=680.5867716471354, r=333.33333333333337, b=670.2534383138021, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 21))], orig='established policies,', text='established policies,', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/31', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=368.33333333333337, t=673.2534383138021, r=380.0, b=665.5867716471354, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 2))], orig='No', text='No', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/32', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=414.3333333333333, t=674.2534383138021, r=485.3333333333333, b=665.9201049804688, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 18))], orig='timeframeinwhichit', text='timeframeinwhichit', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/33', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=267.0, t=669.2534383138021, r=333.0, b=659.9201049804688, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 18))], orig='taken actionsorset', text='taken actionsorset', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/34', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=414.6666666666667, t=663.5867716471354, r=484.6666666666667, b=654.9201049804688, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 17))], orig='aimstohavethesein', text='aimstohavethesein', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/35', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=267.6666666666667, t=658.2534383138021, r=336.66666666666663, b=649.2534383138021, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 20))], orig='targetsforthe topic?', text='targetsforthe topic?', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/36', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=415.0, t=652.5867716471354, r=468.3333333333333, b=643.5867716471354, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 14))], orig='place(ESRS133)', text='place(ESRS133)', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/37', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=298.66666666666663, t=642.5867716471354, r=303.33333333333337, b=637.5867716471354, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 1))], orig='?', text='?', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/38', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=294.33333333333337, t=634.5867716471354, r=307.66666666666663, b=624.5867716471354, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 3))], orig='Yes', text='Yes', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/39', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=434.0, t=630.5867716471354, r=488.6666666666667, b=619.2534383138021, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 15))], orig='The undertaking', text='The undertaking', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/40', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=173.33333333333334, t=621.9201049804688, r=233.66666666666669, b=612.9201049804688, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 15))], orig='Requirement(DR)', text='Requirement(DR)', formatting=None, hyperlink=None),
 TextItem(self_ref='#/texts/41', parent=RefItem(cref='#/pictures/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, meta=None, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=29, bbox=BoundingBox(l=434.3333333333333, t=618.5867716471354, r=489.6666666666667, b=608.9201049804688, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 14))], orig='does nothaveto', text='does nothaveto', formatting=None, hyperlink=None),

:

### Trying to automate it

In [ ]:
x = pd.read_html(r"..\disclosure_standards\raw\ESRS Set 1.html")

In [19]:
from bs4 import BeautifulSoup

def extract_oj_tables(html_path):
    # Load the HTML file
    with open(html_path, "r", encoding="utf-8") as f:
        soup = BeautifulSoup(f, "html.parser")

    # Find all tables with class="oj-table"
    oj_tables = soup.find_all("table", class_="oj-table")

    dataframes = []
    for table in oj_tables:
        # Convert each table HTML into a DataFrame
        df = pd.read_html(str(table))[0]
        dataframes.append(df)

    return dataframes

In [60]:
x = extract_oj_tables(r"..\disclosure_standards\raw\ESRS Set 1.html")

C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]
C:\Users\krish\AppData\Local\Temp\ipykernel_14444\3167887275.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

In [62]:
x[0]

,0,1,2,3
0,Topical ESRS,Sustainability matters covered in topical ESRS,Sustainability matters covered in topical ESRS,Sustainability matters covered in topical ESRS
1,NaN,Topic,Sub-topic,Sub-sub-topics
2,ESRS E1,Climate change,— Climate change adaptation — Climate chang...,NaN
3,—,Climate change adaptation,NaN,NaN
4,—,Climate change mitigation,NaN,NaN
...,...,...,...,...
129,—,Management of relationships with suppliers inc...,NaN,NaN
130,NaN,NaN,— Corruption and bribery,— Prevention and detection including training...
131,—,Corruption and bribery,NaN,NaN
132,—,Prevention and detection including training,NaN,NaN
133,—,Incidents,NaN,NaN